### ISSUE TITLE
Add Arabic language localisation

### ISSUE THREAD

**Issue by abh31000** [vacanza/holidays#1183]
Hi. I saw that your library doesn't support Arabic localisation. As a native speaker, I'd like to contribute to add support for it. Thanks.

**Comment by abh31000** [comment]
> Hi @abh31000,
> 
> it's great to hear that you're willing to add Arabic language support for PH!
> 
> The l10n process is not hard but not ideal yet. A (non language specific) help is available from other contributors. I suggest starting [here](https://github.com/dr-prodigy/python-holidays/blob/master/CONTRIBUTING.rst#localization). And here you can find [several PRs](https://github.com/dr-prodigy/python-holidays/pulls?q=is%3Apr+is%3Aclosed+label%3Alocalization) you could use as an example.
> 
> Let me know in case you have l10n related questions.
> 
> Thanks again, we're very lucky to have a native Arabic speaker in our l10n team!

I'll start working on it right away! If I encounter any difficulties or get stuck on something, I'll make sure to get back to you!

**Comment by abh31000** [comment]
Hi @arkid15r,
There are some updates that should be made to the countries that need Arabic localization. Should I include them in one PR or work on them on a separate one?
Thank you!

**Comment by arkid15r** [comment]
Hey @abh31000,

it's okay to combine multi-country changes if they are related. So a single PR would be fine.

**Comment by abh31000** [comment]
Hi @arkid15r,

This is actually my first l10n work.
I implented the arabic localization for some countries. And they all work as expected. 

Since all Islamic holidays are estimated. Please if you can, tell me how do I add localization for the `estimated_label` attributes of `_add_islamic_calendar_holiday` method in `IslamicHolidays` class.

Thank you.

**Comment by arkid15r** [comment]
Hi @abh31000, that's a totally valid point which requires some attention. I expect the issue to be addressed in https://github.com/dr-prodigy/python-holidays/pull/1140 end of the week -- early next week. I hope this won't block you from submitting your PR

**Comment by arkid15r** [comment]
Hey @abh31000, how is it going with your first l10n attempt? Do you need help with anything (just want to make sure you aren't stuck with some technical difficulty)?
