### ISSUE TITLE
For Canada, 'subdivision' is NULL for the province ON but populated for other provinces

### ISSUE THREAD

**Issue by cybersyn-rayna** [vacanza/holidays#1439]
`subdivision` is `NULL` in the data for province of Ontario. A simple query also shows that ON is the only province that does not appear in the data for Canada at all. However, there are many holidays with `NULL` `subdivision` for Canada. I confirmed that at least some of them are associated with ON based on a Canadian holiday that's unique to that province only - Boxing Day. I would assume all of the `NULL` `subdivision` values are associated with ON.

**Comment by arkid15r** [comment]
Hi @cybersyn-rayna, thank you for bringing this up!

For some (historical?) reason the "ON" subdivision has been set as the default one for Canada holidays implementation. Not sure if that causes the output not meeting your expectations.

Could you add more context as it's not clear what issue you're reporting and it looks like you aren't using our package directly (based on the `NULL` value appearance).

Thank you!
