### ISSUE TITLE
Verify SE holiday calendar

### ISSUE THREAD

**Issue by arkid15r** [vacanza/holidays#1654]
SE has every Saturday included as a public holiday, even though only the banks are closed. Is this intended? If so it is at least misleading as BANK is not the primary category if I understand it correctly.

_Originally posted by @nick2202 in https://github.com/vacanza/python-holidays/issues/1646#issuecomment-1903926225_

**Comment by KJhellico** [comment]
Actually, it's every Sunday we have as public holiday (with special arg `include_sundays=True`). I've always wondered how Sundays in Sweden differ from Sundays in other countries (where they are also days off). As far as I understood, the reason for this difference is that

> In Sweden, public holidays are defined in the Swedish Constitution as a Sunday, or another day in a list of public holidays

([from Wiki, machine translation to English](https://sv.wikipedia.org/wiki/Helgdagar_i_Sverige))

Is this a enough reason for us to include all Sundays in the list of holidays? Maybe we could at least set `include_sundays` default value to `False`? (exactly how it's done for Norway now)

**Comment by PPsyrius** [comment]
Have we ever reached a conclusion on this?

**Comment by arkid15r** [comment]
> Have we ever reached a conclusion on this?

It doesn't seem so. I'd like to change the Sundays situation for SE in `v1` but before that it'd be great to have some input from users familiar with the context. 

I'd keep it as is for `v0` unless someone has strong reasons for opposite.
