### ISSUE TITLE
Add Filipino Localization for the Philippines Holiday Class

### ISSUE THREAD

**Issue by arkid15r** [vacanza/holidays#2067]
The `vacanza/holidays` package currently supports public holidays for the Philippines, as defined in the [holidays/countries/philippines.py](https://github.com/vacanza/holidays/blob/1e81ae88f0d12870962cb498006c3f20e4a3d335/holidays/countries/philippines.py) file. However, the package lacks Filipino translations for the holiday names.  It seems we should use `fil` ISO 639-2 code as described [here](https://en.wikipedia.org/wiki/Filipino_language) and [here](https://en.wikipedia.org/wiki/Languages_of_the_Philippines).

The `holidays` l10n documentation section -- https://holidays.readthedocs.io/en/latest/contributing.html#localization

Some l10n PR examples:
  - https://github.com/vacanza/holidays/pull/946
  - https://github.com/vacanza/holidays/pull/1341
  - https://github.com/vacanza/holidays/pull/2060
  - [More PRs](https://github.com/vacanza/holidays/pulls?q=is%3Apr+is%3Aclosed+label%3Al10n) w/ `l10n` label

Personally I would prefer to see `fil_PH` as the default but `en_PH` would also work.

@code-leen we'd appreciate your help with this a lot!

**Comment by PPsyrius** [comment]
@arkid15r I think it might be the best to just default to `Tagalog (tl)` instead of `Filipino (fil)` - as that's exactly what the ISO is using here https://www.[iso.org/obp/ui/#iso:code:3166:PH](https://www.iso.org/obp/ui/#iso:code:3166:PH)

**Comment by arkid15r** [comment]
Based on my research Philippines has 2 [official languages ](https://en.wikipedia.org/wiki/Languages_of_the_Philippines): Filipino and English. Even though Filipino is Tagalog based language it's different (https://en.wikipedia.org/wiki/Filipino_language)

> It is a [standardized variety](https://en.wikipedia.org/wiki/Standard_language) of the native language [Tagalog](https://en.wikipedia.org/wiki/Tagalog_language),[[3]](https://en.wikipedia.org/wiki/Filipino_language#cite_note-Filipino-Tagalog-Not-So-Simple-3) spoken and written in [Metro Manila](https://en.wikipedia.org/wiki/Metro_Manila), the National Capital Region, and in other urban centers of the archipelago.[[4]](https://en.wikipedia.org/wiki/Filipino_language#cite_note-Resolution-92-1-4) The [1987 Constitution](https://en.wikipedia.org/wiki/Constitution_of_the_Philippines) mandates that Filipino be further enriched and developed by the other [languages of the Philippines](https://en.wikipedia.org/wiki/Languages_of_the_Philippines).[[5]](https://en.wikipedia.org/wiki/Filipino_language#cite_note-5)
