### ISSUE TITLE
`Language-Team` name standardization in l10n files

### ISSUE THREAD

**Issue by PPsyrius** [vacanza/holidays#2094]
Right now there's a mix between the older `"Language-Team: Holidays localization team\n"` and newer `"Language-Team: Holidays Localization Team\n"` in localization file headers at the moment, and we should probably switch all former ones to the new standard.

**Comment by arkid15r** [comment]
Nice attention to detail, I appreciate that 👍 
I'm fine with any option as long as it's consistent. Do you like `"Language-Team: Holidays Localization Team\n"` better?

**Comment by PPsyrius** [comment]
The latter is what we gets at the moment when running `make l10n` for newly added localizations - if we choose to kept the old format, just make sure to update `make l10n` as well 🙏 

I'm fine with either way myself but a bit leans towards the latter.
