### ISSUE TITLE
Is it possible to import a specific country's holidays to Google calendar?

### ISSUE THREAD

**Issue by rti2** [vacanza/holidays#2160]
I wanna add my country's holidays to google calendar. Is it possible?
Google calendar supports iCal.

**Comment by arkid15r** [comment]
@rti2 thank for your question.
We don't provide this functionality out of the box. This sounds like a good feature request to me.

Could you add more details about your use case?

**Comment by rti2** [comment]
For importing into google calendar

**Comment by arkid15r** [comment]
Yeah, we already have this info from your previous post. I was hoping the get more details about your use case (e.g. single year / multiple years, holiday category support, country subdivisions, multiple countries, etc). 

Thank you.

**Comment by rti2** [comment]
Single country, single year (Isn't the link updating ?), official holidays, just a single country

**Comment by arkid15r** [comment]
I've added it to our `v1` plans.
