### ISSUE TITLE
Strange behavior in Ru holidays (Help needed)

### ISSUE THREAD

**Issue by toptalo** [vacanza/holidays#2188]
For some reason package has not correctly works for Russian holidays

My Code:
```python
import holidays
ru_holidays = holidays.country_holidays('RU')
print('2024-12-30' in ru_holidays)
#Output False
```

In file holidays/holidays/countries/russia.py (https://github.com/vacanza/holidays/blob/2aa829a906fb6e3cbf60636317eaa3a49e78698f/holidays/countries/russia.py#L317)
I can see that 2024-12-30 is in RussiaStaticHolidays

Can anybody help me to get correct output for that date?
Maybe there is some other method that I should be calling

**Comment by arkid15r** [comment]
Works for me. 
What's your `holidays` version?

**Comment by toptalo** [comment]
holidays==0.27.1 🤦 

That it! I forgot that this project is wery old an uses python 3.7
@arkid15r thanhs for quick response
